version: 2.1

# Define the jobs for the frontend and backend
jobs:
  # build backend job
  build-backend:
    docker:
      - image: 'circleci/node:13.8.0'
    steps:
      - checkout
      # run install backend dependencies
      - run:
          name: Install
          command: |
            cd backend
            npm install
      # run build backend dependencies
      - run:
          name: Build
          command: |
            cd backend
            npm run build

  # test backend job
  test-backend:
    docker:
      - image: 'circleci/node:13.8.0'
    steps:
      - checkout
      # run install backend dependencies for test

  # build frontend job
  build-frontend:
    docker:
      - image: 'circleci/node:13.8.0'
    steps:
      - checkout
      # run install frontend dependencies
      - run:
          name: Install
          command: |
            cd frontend
            npm run install

      # run build frontend dependencies
      - run:
          name: Build
          command: |
            cd frontend
            npm run build

# Define workflows for the frontend and backend
workflows:
  # backend workflows
  backend:
    jobs:
      - build-backend

  # frontend workflows
  frontend:
    jobs:
      - build-frontend
