version: 2.1

# Define the jobs for the frontend and backend
jobs:
  # build backend job
  build-backend:
    docker:
      - image: 'circleci/node:13.8.0'
    steps:
      - checkout
      # run install backend dependencies
      - run:
          name: Install
          command: |
            cd backend
            npm install
      # run build backend dependencies
      - run:
          name: Build
          command: |
            cd backend
            npm run build

  # test backend job
  test-backend:
    docker:
      - image: 'circleci/node:13.8.0'
    steps:
      - checkout
      # run install backend dependencies for test
      - run:
          name: Build
          command: |
            cd backend
            npm install

      # run test
      - run:
          name: Test
          command: |
            cd backend
            npm install
            npm run test

  # analyse backend job
  analyse-backend:
    docker:
      - image: 'circleci/node;13.8.0'
    steps:
      - checkout
      # run install backend dependencies for analyse
      - run:
          name: Build
          command: |
            cd backend
            npm install
      # audit backend
      - run:
          name: Build
          command: |
            cd backend
            npm audit --audit-level=critical

  # build frontend job
  build-frontend:
    docker:
      - image: 'circleci/node:13.8.0'
    steps:
      - checkout
      # run install frontend dependencies
      - run:
          name: Install
          command: |
            cd frontend
            npm install

      # run build frontend dependencies
      - run:
          name: Build
          command: |
            cd frontend
            npm run build

  # test frontend job
  test-frontend:
    docker:
      - image: 'circleci/node:13.8.0'
    steps:
      - checkout
      # run install frontend dependencies
      - run:
          name: Install
          command: |
            cd frontend
            npm install

      # run test
      - run:
          name: Test
          command: |
            cd frontend
            npm install
            npm run test

  analyse-frontend:
    docker:
      - image: 'circleci/node:13.8.0'
    steps:
      - checkout
      # run install frontend dependencies
      - run:
          name: Build
          command: |
            cd frontend
            npm install

      # audit frontend
      - run:
          name: Build
          command: |
            cd frontend
            npm audit --audit-level=critical

# Define workflows for the frontend and backend
workflows:
  # backend workflows
  backend:
    jobs:
      - build-backend
      - test-backend:
          requires:
            - build-backend
      - analyse-backend:
          requires:
            - test-backend

  # frontend workflows
  frontend:
    jobs:
      - build-frontend
      - test-frontend:
          requires:
            - build-frontend
      - analyse-frontend:
          requires:
            - test-frontend
